#Linear Regression


In [ ]:
'''Let my equation is y = 7x + 1'''

'Let my equation is y = 7x + 1'

In [ ]:
import random
import numpy as np

In [ ]:
''' Without Error '''
num_samples = 4
x_values = [random.uniform(-10, 10) for _ in range(num_samples)]

# Calculate corresponding y values
y_values = [(7*x + 1) for x in x_values]

# Print the generated pairs of (x, y)
for x, y in zip(x_values, y_values):
    print(f"x = {x}, y = {y}")

x = 4.748097233723199, y = 34.23668063606239
x = -8.15749491223514, y = -56.10246438564599
x = 6.833143998929913, y = 48.83200799250939
x = -3.112425656964728, y = -20.786979598753096


In [ ]:
# ''' With Error '''

# num_samples = 4
# x_values = [random.uniform(-10, 10) for _ in range(num_samples)]

# # Calculate corresponding y values
# y_values = [(7*x + 1) + random.uniform(-1.0, 0.5) for x in x_values]

# # Print the generated pairs of (x, y)
# for x, y in zip(x_values, y_values):
#     print(f"x = {x}, y = {y}")

In [ ]:
''' Prepare the augmented matrix '''

ones_column = np.ones((len(x_values), 1))
values_column = np.array(x_values).reshape(-1, 1)
augmented_matrix = np.hstack((ones_column, values_column))

print("Augmented Matrix:")
print(augmented_matrix)


'''    Another way

augmented_matrix = []
for i in range(len(x_values)):
  l = []
  l.append(1)
  l.append(x_values[i])
  augmented_matrix.append(l)
print(augmented_matrix)

'''

Augmented Matrix:
[[ 1.          4.74809723]
 [ 1.         -8.15749491]
 [ 1.          6.833144  ]
 [ 1.         -3.11242566]]


'    Another way\n\naugmented_matrix = []\nfor i in range(len(x_values)):\n  l = []\n  l.append(1)\n  l.append(x_values[i])\n  augmented_matrix.append(l)\nprint(augmented_matrix)\n\n'

In [ ]:
''' Get the matrix transpose'''
augmented_matrix_transpose = np.transpose(augmented_matrix)
print(augmented_matrix_transpose)

[[ 1.          1.          1.          1.        ]
 [ 4.74809723 -8.15749491  6.833144   -3.11242566]]


In [ ]:
''' Multiply X transpose by X'''
result = np.dot(augmented_matrix_transpose, augmented_matrix)

print("Result of X multiplied by its transpose:")
print(result)

Result of X multiplied by its transpose:
[[  4.           0.31132066]
 [  0.31132066 145.46820096]]


In [ ]:
''' Get the inverse of the matrix '''
inverse_matrix = np.linalg.inv(result)
print(inverse_matrix)

[[ 0.25004165 -0.00053512]
 [-0.00053512  0.0068755 ]]


In [ ]:
''' Get the weight vector '''

weight_vector= np.dot(np.dot(inverse_matrix, augmented_matrix_transpose), y_values)
print(weight_vector)

[1. 7.]


In [ ]:
''' Test the output should be 64 if i substitiuted with 9'''
value = weight_vector[1]*9 + weight_vector[0]
print(value)

64.0
