In [ ]:
import pandas as pd
import numpy as np
from keras.datasets import mnist
from sklearn.metrics import confusion_matrix

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
X_train_flattened = X_train.reshape((X_train.shape[0], -1)) / 255.0
X_test_flattened = X_test.reshape((X_test.shape[0], -1)) / 255.0
num_classes = 10
y_train_onehot = np.eye(num_classes)[y_train]
y_test_onehot = np.eye(num_classes)[y_test]

In [ ]:
print(X_train_flattened.shape)
print(X_test_flattened.shape)
print(y_train_onehot.shape)
print(y_test_onehot.shape)

(60000, 784)
(10000, 784)
(60000, 10)
(10000, 10)


In [ ]:
input = X_train_flattened.shape[1]
hidden = 128 #try
output = num_classes

weights_input_hidden = np.random.randn(input, hidden)
biases_input =np.zeros((1, hidden))
weights_hidden = np.random.randn(hidden, output)
biases_hidden =np.zeros((1, output))

In [ ]:
n = 0.01
epochs = 20
predictions = 0
for epoch in range(epochs):
  for i in range(len(X_train_flattened)):
  #Forward
    # i = 0
    feature = X_train_flattened[i]
    output_input_hidden = sigmoid(np.dot(feature.T, weights_input_hidden)+biases_input)
    output_hidden_output = sigmoid(np.dot(output_input_hidden,weights_hidden)+biases_hidden)
    #Backward
    output_error = y_train_onehot[i] - output_hidden_output
    segma_output = sigmoid_derivative(output_hidden_output) * output_error

    change_output = np.dot(output_input_hidden.T, segma_output) * n
    weights_hidden = weights_hidden + change_output

    hidden_error= np.dot(segma_output,weights_hidden.T)
    segma_hidden = sigmoid_derivative(output_input_hidden) * hidden_error

    change_hidden = np.dot(feature.reshape(-1, 1), segma_hidden) * n
    weights_input_hidden = weights_input_hidden + change_hidden
  output_input_hidden = sigmoid(np.dot(X_test_flattened, weights_input_hidden)+biases_input)
  output_hidden_output = sigmoid(np.dot(output_input_hidden,weights_hidden)+biases_hidden)
  predictions = np.argmax(output_hidden_output, axis = 1)
  accuracy = np.mean(predictions == np.argmax(y_test_onehot, axis = 1))

  print(f'Epoch {epoch+1}/{epochs}, Test Accuracy: {accuracy}')
conf_matrix = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(conf_matrix)
conf_df = pd.DataFrame(conf_matrix, index=[f'Actual {i}' for i in range(10)], columns=[f'Predicted {i}' for i in range(10)])
print(conf_df)



<ipython-input-37-61cfbe30c85c>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Epoch 1/20, Test Accuracy: 0.852
Epoch 2/20, Test Accuracy: 0.8296
Epoch 3/20, Test Accuracy: 0.8506
Epoch 4/20, Test Accuracy: 0.858
Epoch 5/20, Test Accuracy: 0.8657
Epoch 6/20, Test Accuracy: 0.8718
Epoch 7/20, Test Accuracy: 0.8677
Epoch 8/20, Test Accuracy: 0.8696
Epoch 9/20, Test Accuracy: 0.8728
Epoch 10/20, Test Accuracy: 0.8716
Epoch 11/20, Test Accuracy: 0.8679
Epoch 12/20, Test Accuracy: 0.8672
Epoch 13/20, Test Accuracy: 0.868
Epoch 14/20, Test Accuracy: 0.8615
Epoch 15/20, Test Accuracy: 0.8672
Epoch 16/20, Test Accuracy: 0.8698
Epoch 17/20, Test Accuracy: 0.8664
Epoch 18/20, Test Accuracy: 0.8588
Epoch 19/20, Test Accuracy: 0.855
Epoch 20/20, Test Accuracy: 0.8531
Confusion Matrix:
[[ 937    1    5    2    2    6   16    1    9    1]
 [   0 1066    2    3    0    2    3    1   57    1]
 [  15   16  790   46   17    3   29   23   90    3]
 [   7    2   22  889    2   26    6   11   42    3]
 [   1   10    3    0  870    2   14    3   36   43]
 [  44    8    5   44   16  62